// Copyright (c) 2025 Krishna Teja Mekala (Kriaa Systems). All rights reserved.

use super::build_cs_parser::parse_build_cs;
use super::clangd_config_generator::{generate_ue_clangd_config, write_clangd_config};
use super::defines_builder::build_all_defines;
use super::include_path_builder::{infer_module_include_paths, IncludePathBuilder};
use super::project_model::{ModuleType, UEModule, UEPlugin, UEProject, UProjectFile};
use super::uplugin_parser::parse_uplugin;
use super::uproject_parser::parse_uproject;
use crate::solution::{find_solution_file, parse_solution};
use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

/// Macro completion helper header content (based on unreal-clangd)
/// This file is force-included to provide UE macro completions
const MACRO_HELPER_CONTENT: &str = r#"#pragma once
// Auto-generated by Cherry IDE for Unreal Engine macro completions
// This file is force-included via /FI flag for clangd

// Core UObject macros (UPROPERTY, UFUNCTION, UCLASS, USTRUCT, etc.)
#include "UObject/ObjectMacros.h"

// Delegate macros (DECLARE_DELEGATE, DECLARE_MULTICAST_DELEGATE, etc.)
#include "Delegates/DelegateCombinations.h"

// Logging macros (UE_LOG, etc.)
#include "Logging/LogMacros.h"

// Assertion macros (check, ensure, verify, etc.)
#include "Misc/AssertionMacros.h"

// Stats macros (STAT_*, DECLARE_STATS_GROUP, etc.)
#include "Stats/Stats.h"

// Network replication macros (DOREPLIFETIME, etc.)
#include "Net/UnrealNetwork.h"

// Generated code support
#include "UObject/Class.h"
"#;

/// Completion helper cpp content
const COMPLETION_HELPER_CPP: &str = r#"// Auto-generated by Cherry IDE for clangd completions
// This file is added to compile_commands.json for macro parsing
#include "macroCompletionHelper.h"
"#;

/// Entry in compile_commands.json
#[derive(Debug, Clone, Serialize, Deserialize)]
struct CompileCommand {
    file: String,
    directory: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    command: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    arguments: Option<Vec<String>>,
}

pub struct CherrySightManager {
    project_root: PathBuf,
    uproject_path: PathBuf,
}

impl CherrySightManager {
    pub fn new(project_root: PathBuf, uproject_path: PathBuf) -> Self {
        Self {
            project_root,
            uproject_path,
        }
    }

    /// Main entry point: auto-configure CherrySight on workspace open
    pub fn auto_configure(&self) -> Result<()> {
        log::info!("Starting UE CherrySight auto-configuration...");

        // Step 1: Create .cherry directory
        let cherry_dir = self.project_root.join(".cherry");
        if !cherry_dir.exists() {
            std::fs::create_dir_all(&cherry_dir)
                .with_context(|| format!("Failed to create .cherry directory: {}", cherry_dir.display()))?;
            log::info!("Created .cherry directory");
        }

        // Step 2: Parse .uproject
        log::info!("Parsing .uproject file: {}", self.uproject_path.display());
        let uproject_file = parse_uproject(&self.uproject_path)?;
        log::info!(
            "Found {} modules and {} plugin references",
            uproject_file.modules.len(),
            uproject_file.plugins.len()
        );

        // Step 3: Detect engine path
        log::info!("Detecting engine path...");
        let engine_path = self.detect_engine_path(&uproject_file.engine_association)?;
        log::info!("Engine path: {}", engine_path.display());

        // Step 4: Create macro helper files
        log::info!("Creating macro helper files...");
        let macro_helper_path = self.create_macro_helper_files(&cherry_dir)?;
        log::info!("Created macro helper at: {}", macro_helper_path.display());

        // Step 5: Discover and parse plugins
        log::info!("Discovering plugins...");
        let plugins = self.discover_plugins(&uproject_file, &engine_path)?;
        log::info!("Discovered {} plugins", plugins.len());

        // Step 6: Parse project modules
        log::info!("Parsing project modules...");
        let project_modules = self.parse_project_modules(&uproject_file)?;
        log::info!("Parsed {} project modules", project_modules.len());

        // Step 7: Build project model
        let project = UEProject {
            uproject_path: self.uproject_path.clone(),
            project_name: self
                .uproject_path
                .file_stem()
                .unwrap()
                .to_string_lossy()
                .to_string(),
            engine_association: uproject_file.engine_association.clone(),
            engine_path: Some(engine_path.clone()),
            modules: project_modules,
            plugins,
            target_platforms: uproject_file.target_platforms.clone(),
        };

        // Step 8: Build include paths
        log::info!("Building include paths...");
        let builder = IncludePathBuilder::new(engine_path.clone(), self.project_root.clone());
        let include_paths = builder.build_all_include_paths(&project);
        log::info!("Generated {} include paths", include_paths.len());

        // Step 9: Build defines
        log::info!("Building preprocessor defines...");
        let defines = build_all_defines(&project, "Windows", "Development");
        log::info!("Generated {} defines", defines.len());

        // Step 10: Add completionHelper.cpp to compile_commands.json
        log::info!("Updating compile_commands.json with completionHelper.cpp...");
        if let Err(e) = self.add_completion_helper_to_compile_commands(&cherry_dir) {
            log::warn!("Failed to add completionHelper.cpp to compile_commands.json: {}", e);
        }

        // Step 11: Detect clang-cl path
        let compiler_path = find_clang_cl_path();
        if let Some(ref path) = compiler_path {
            log::info!("Found clang-cl at: {}", path);
        } else {
            log::info!("clang-cl not found, using default compiler");
        }

        // Step 12: Generate enhanced .clangd config
        log::info!("Generating enhanced .clangd configuration...");
        let config = generate_ue_clangd_config(
            &self.project_root,
            &cherry_dir,
            Some(&macro_helper_path),
            compiler_path.as_deref(),
            &include_paths,
            &defines,
        )?;

        // Step 13: Write .clangd
        write_clangd_config(&config, &self.project_root)?;

        log::info!("UE CherrySight auto-configuration complete!");
        Ok(())
    }

    /// Create macro helper files in .cherry directory
    fn create_macro_helper_files(&self, cherry_dir: &Path) -> Result<PathBuf> {
        // Create macroCompletionHelper.h
        let macro_helper_path = cherry_dir.join("macroCompletionHelper.h");
        std::fs::write(&macro_helper_path, MACRO_HELPER_CONTENT)
            .with_context(|| format!("Failed to create {}", macro_helper_path.display()))?;

        // Create completionHelper.cpp
        let completion_helper_path = cherry_dir.join("completionHelper.cpp");
        std::fs::write(&completion_helper_path, COMPLETION_HELPER_CPP)
            .with_context(|| format!("Failed to create {}", completion_helper_path.display()))?;

        Ok(macro_helper_path)
    }

    /// Add completionHelper.cpp entry to compile_commands.json
    fn add_completion_helper_to_compile_commands(&self, cherry_dir: &Path) -> Result<()> {
        let compile_commands_path = cherry_dir.join("compile_commands.json");
        if !compile_commands_path.exists() {
            log::info!("compile_commands.json not found in .cherry, skipping completionHelper addition");
            return Ok(());
        }

        // Read existing compile_commands.json
        let content = std::fs::read_to_string(&compile_commands_path)
            .with_context(|| format!("Failed to read {}", compile_commands_path.display()))?;

        let mut commands: Vec<CompileCommand> = serde_json::from_str(&content)
            .with_context(|| "Failed to parse compile_commands.json")?;

        // Check if completionHelper.cpp already exists
        let helper_file = cherry_dir.join("completionHelper.cpp");
        let helper_file_str = helper_file.display().to_string().replace("\\", "/");

        if commands.iter().any(|c| c.file.contains("completionHelper.cpp")) {
            log::info!("completionHelper.cpp already in compile_commands.json");
            return Ok(());
        }

        // Get a reference command to copy arguments from
        if let Some(ref_cmd) = commands.first().cloned() {
            let new_entry = CompileCommand {
                file: helper_file_str,
                directory: cherry_dir.display().to_string().replace("\\", "/"),
                command: ref_cmd.command.clone(),
                arguments: ref_cmd.arguments.clone(),
            };

            commands.push(new_entry);

            // Write back
            let new_content = serde_json::to_string_pretty(&commands)
                .context("Failed to serialize compile_commands.json")?;
            std::fs::write(&compile_commands_path, new_content)
                .with_context(|| format!("Failed to write {}", compile_commands_path.display()))?;

            log::info!("Added completionHelper.cpp to compile_commands.json");
        }

        Ok(())
    }

    /// Detect engine path from engine association or solution file
    fn detect_engine_path(&self, engine_association: &str) -> Result<PathBuf> {
        // Try to find engine path from solution file
        if let Some(sln_path) = find_solution_file(&self.project_root) {
            log::info!("Found solution file: {}", sln_path.display());
            if let Ok(solution) = parse_solution(&sln_path) {
                if let Some(engine_path) = solution.detect_engine_path() {
                    log::info!("Detected engine path from solution: {}", engine_path.display());
                    return Ok(engine_path);
                }
            }
        }

        // Fallback: Try common paths
        let common_paths = vec![
            PathBuf::from(format!("W:\\Softwares\\UE_{}", engine_association)),
            PathBuf::from(format!("C:\\Program Files\\Epic Games\\UE_{}", engine_association)),
            PathBuf::from(format!("W:\\Softwares\\UnrealEngine-{}", engine_association)),
        ];

        for path in common_paths {
            if path.exists() {
                log::info!("Found engine at common path: {}", path.display());
                return Ok(path);
            }
        }

        anyhow::bail!(
            "Could not detect engine path for engine association: {}",
            engine_association
        )
    }

    /// Discover and parse all plugins (project plugins and enabled engine plugins)
    fn discover_plugins(
        &self,
        uproject_file: &UProjectFile,
        engine_path: &Path,
    ) -> Result<Vec<UEPlugin>> {
        let mut plugins = Vec::new();

        // Discover project plugins
        let project_plugins_dir = self.project_root.join("Plugins");
        if project_plugins_dir.exists() {
            plugins.extend(self.scan_plugins_directory(&project_plugins_dir, false)?);
        }

        // Discover enabled engine plugins
        for plugin_ref in &uproject_file.plugins {
            if !plugin_ref.enabled {
                continue;
            }

            // Try to find the plugin in engine
            let engine_plugins_dir = engine_path.join("Plugins");
            if let Some(plugin) = self.find_plugin(&plugin_ref.name, &engine_plugins_dir, true)? {
                plugins.push(plugin);
            }
        }

        Ok(plugins)
    }

    /// Scan a plugins directory for .uplugin files
    fn scan_plugins_directory(
        &self,
        plugins_dir: &Path,
        is_engine_plugin: bool,
    ) -> Result<Vec<UEPlugin>> {
        let mut plugins = Vec::new();

        for entry in WalkDir::new(plugins_dir)
            .max_depth(2)
            .into_iter()
            .filter_map(|e| e.ok())
        {
            if entry.path().extension().and_then(|s| s.to_str()) == Some("uplugin") {
                match self.parse_plugin_file(entry.path(), is_engine_plugin) {
                    Ok(plugin) => {
                        log::info!("Discovered plugin: {} ({} modules)", plugin.name, plugin.modules.len());
                        plugins.push(plugin);
                    }
                    Err(e) => {
                        log::warn!("Failed to parse plugin {}: {}", entry.path().display(), e);
                    }
                }
            }
        }

        log::info!("Scanned {} from {}: found {} plugins",
                   if is_engine_plugin { "engine plugins" } else { "project plugins" },
                   plugins_dir.display(),
                   plugins.len());
        Ok(plugins)
    }

    /// Find a specific plugin by name
    fn find_plugin(
        &self,
        plugin_name: &str,
        plugins_dir: &Path,
        is_engine_plugin: bool,
    ) -> Result<Option<UEPlugin>> {
        for entry in WalkDir::new(plugins_dir)
            .max_depth(2)
            .into_iter()
            .filter_map(|e| e.ok())
        {
            if entry.path().extension().and_then(|s| s.to_str()) == Some("uplugin") {
                if let Some(file_stem) = entry.path().file_stem() {
                    if file_stem.to_string_lossy() == plugin_name {
                        return Ok(Some(
                            self.parse_plugin_file(entry.path(), is_engine_plugin)?
                        ));
                    }
                }
            }
        }

        Ok(None)
    }

    /// Parse a .uplugin file and its modules
    fn parse_plugin_file(&self, uplugin_path: &Path, is_engine_plugin: bool) -> Result<UEPlugin> {
        let uplugin_file = parse_uplugin(uplugin_path)?;
        let plugin_root = uplugin_path.parent().unwrap().to_path_buf();

        let mut modules = Vec::new();
        for module_desc in &uplugin_file.modules {
            if let Ok(module) = self.parse_module_from_plugin(
                &module_desc.name,
                &module_desc.module_type,
                &plugin_root,
            ) {
                modules.push(module);
            }
        }

        Ok(UEPlugin {
            name: uplugin_path
                .file_stem()
                .unwrap()
                .to_string_lossy()
                .to_string(),
            uplugin_path: uplugin_path.to_path_buf(),
            plugin_root: plugin_root.clone(),
            version: uplugin_file.file_version,
            friendly_name: None,
            modules,
            plugin_dependencies: uplugin_file
                .plugins
                .iter()
                .map(|p| p.name.clone())
                .collect(),
            is_engine_plugin,
            can_contain_content: false,
        })
    }

    /// Parse project modules from .uproject
    fn parse_project_modules(&self, uproject_file: &UProjectFile) -> Result<Vec<UEModule>> {
        let mut modules = Vec::new();

        for module_desc in &uproject_file.modules {
            let source_path = self.project_root.join("Source").join(&module_desc.name);
            let build_cs_path = source_path.join(format!("{}.Build.cs", module_desc.name));

            if !build_cs_path.exists() {
                log::warn!(
                    "Build.cs not found for module {}: {}",
                    module_desc.name,
                    build_cs_path.display()
                );
                continue;
            }

            let (dependencies, include_paths, defines) = parse_build_cs(&build_cs_path)
                .with_context(|| format!("Failed to parse {}", build_cs_path.display()))?;

            let mut inferred_includes = infer_module_include_paths(&source_path);
            inferred_includes.extend(include_paths.inferred_paths.clone());

            // Also add the source directory itself as an include path
            // This handles modules without Public/Private folders
            if !inferred_includes.contains(&source_path) {
                inferred_includes.push(source_path.clone());
            }

            modules.push(UEModule {
                name: module_desc.name.clone(),
                module_type: ModuleType::from_str(&module_desc.module_type),
                loading_phase: module_desc.loading_phase.clone(),
                source_path,
                build_cs_path,
                dependencies,
                include_paths: super::project_model::IncludePaths {
                    public_include_paths: include_paths.public_include_paths,
                    private_include_paths: include_paths.private_include_paths,
                    inferred_paths: inferred_includes,
                },
                defines,
            });
        }

        Ok(modules)
    }

    /// Parse a module from a plugin
    fn parse_module_from_plugin(
        &self,
        module_name: &str,
        module_type: &str,
        plugin_root: &Path,
    ) -> Result<UEModule> {
        let source_path = plugin_root.join("Source").join(module_name);
        let build_cs_path = source_path.join(format!("{}.Build.cs", module_name));

        if !build_cs_path.exists() {
            anyhow::bail!(
                "Build.cs not found for plugin module {}: {}",
                module_name,
                build_cs_path.display()
            );
        }

        let (dependencies, include_paths, defines) = parse_build_cs(&build_cs_path)?;

        let mut inferred_includes = infer_module_include_paths(&source_path);
        inferred_includes.extend(include_paths.inferred_paths.clone());

        // Also add the source directory itself as an include path
        if !inferred_includes.contains(&source_path) {
            inferred_includes.push(source_path.clone());
        }

        Ok(UEModule {
            name: module_name.to_string(),
            module_type: ModuleType::from_str(module_type),
            loading_phase: "Default".to_string(),
            source_path,
            build_cs_path,
            dependencies,
            include_paths: super::project_model::IncludePaths {
                public_include_paths: include_paths.public_include_paths,
                private_include_paths: include_paths.private_include_paths,
                inferred_paths: inferred_includes,
            },
            defines,
        })
    }
}

/// Find clang-cl.exe on the system
/// Searches environment variables: PATH, LLVM_PATH, LLVM_HOME
pub fn find_clang_cl_path() -> Option<String> {
    // 1. Search PATH environment variable
    if let Ok(path_var) = std::env::var("PATH") {
        for path in std::env::split_paths(&path_var) {
            let clang_cl = path.join("clang-cl.exe");
            if clang_cl.exists() {
                log::info!("Found clang-cl in PATH: {}", clang_cl.display());
                return Some(clang_cl.display().to_string());
            }
        }
    }

    // 2. Check LLVM_PATH environment variable
    if let Ok(llvm_path) = std::env::var("LLVM_PATH") {
        let clang_cl = PathBuf::from(&llvm_path).join("bin").join("clang-cl.exe");
        if clang_cl.exists() {
            log::info!("Found clang-cl via LLVM_PATH: {}", clang_cl.display());
            return Some(clang_cl.display().to_string());
        }
    }

    // 3. Check LLVM_HOME environment variable
    if let Ok(llvm_home) = std::env::var("LLVM_HOME") {
        let clang_cl = PathBuf::from(&llvm_home).join("bin").join("clang-cl.exe");
        if clang_cl.exists() {
            log::info!("Found clang-cl via LLVM_HOME: {}", clang_cl.display());
            return Some(clang_cl.display().to_string());
        }
    }

    // 4. Check LLVM_DIR environment variable
    if let Ok(llvm_dir) = std::env::var("LLVM_DIR") {
        let clang_cl = PathBuf::from(&llvm_dir).join("bin").join("clang-cl.exe");
        if clang_cl.exists() {
            log::info!("Found clang-cl via LLVM_DIR: {}", clang_cl.display());
            return Some(clang_cl.display().to_string());
        }
    }

    log::info!("clang-cl.exe not found in PATH or LLVM environment variables");
    None
}
