[package]
name = "unreal_panel"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"
description = "Unreal Engine output panel for Cherry IDE"

[lints]
workspace = true

[lib]
path = "src/unreal_panel.rs"
doctest = false

[dependencies]
anyhow.workspace = true
cherry_link.workspace = true
collections.workspace = true
gpui.workspace = true
settings.workspace = true
ui.workspace = true
workspace.workspace = true
